<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class _Class extends Model
{
    protected $primaryKey = 'Class_Id';

    protected $table = 'classes';

    protected $with = ['baseClass', 'section'];

    public function baseClass() {
        return $this->belongsTo(BaseClass::class, 'BaseClass_Id');
    }

    public function section() {
        return $this->belongsTo(Section::class, 'Section_Id');
    }

    public function students() {
        return $this->belongsToMany(Student::class, 'class_student', 'Class_Id')->withPivot('PrelimGrade', 'FinalGrade', 'SemestralGrade', 'TransmutedGrade');
    }

    public function delete()
    {
        //iterate all students of this course
        foreach ($this->students()->get() as $student) {
            //iterate all requirements of this course
            foreach ($this->baseClass->course->requirements()->get() as $requirement) {
                //iterate all student evaluations related to the requirement
                foreach ($student->SOEvaluations()->where('Requirement_Id', $requirement->Requirement_Id)->get() as $SOEvals) {
                    $SOEvals->delete();
                }
            }
        }

        $this->students()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
